[2023-12-27 16:59:05,469] INFO [GroupCoordinator 0]: Member loko-scheduler-7a96fba3-fcdd-4a20-b51c-8812e5d0d62e in group my-loco-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:06,216] WARN Client session timed out, have not heard from server in 3975775ms for session id 0x10023a87fc80002 (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:05,897] INFO Expiring session 0x10023a87fc80002, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2023-12-27 16:59:08,537] INFO [GroupCoordinator 0]: Preparing to rebalance group my-loco-group in state PreparingRebalance with old generation 200 (__consumer_offsets-2) (reason: removing member loko-scheduler-7a96fba3-fcdd-4a20-b51c-8812e5d0d62e on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:10,515] WARN Session 0x10023a87fc80002 for server localhost/[0:0:0:0:0:0:0:1]:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 3975775ms for session id 0x10023a87fc80002
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1257)
[2023-12-27 16:59:12,168] INFO [GroupCoordinator 0]: Group my-loco-group with generation 201 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:18,691] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:19,316] INFO Socket connection established, initiating session, client: /[0:0:0:0:0:0:0:1]:59744, server: localhost/[0:0:0:0:0:0:0:1]:2181 (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:19,374] INFO Invalid session 0x10023a87fc80002 for client /[0:0:0:0:0:0:0:1]:59744, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2023-12-27 16:59:20,438] WARN Unable to reconnect to ZooKeeper service, session 0x10023a87fc80002 has expired (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:20,441] WARN Session 0x10023a87fc80002 for server localhost/[0:0:0:0:0:0:0:1]:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x10023a87fc80002 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1438)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[2023-12-27 16:59:20,447] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2023-12-27 16:59:20,972] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2023-12-27 16:59:20,977] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@57c03d88 (org.apache.zookeeper.ZooKeeper)
[2023-12-27 16:59:20,441] INFO EventThread shut down for session: 0x10023a87fc80002 (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:22,334] INFO [LocalLog partition=__consumer_offsets-2, dir=G:\P79\GAP\tmp\kafka-logs] Rolled new log segment at offset 517 in 1953 ms. (kafka.log.LocalLog)
[2023-12-27 16:59:21,483] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2023-12-27 16:59:24,184] INFO [ProducerStateManager partition=__consumer_offsets-2]Wrote producer snapshot at offset 517 with 0 producer ids in 558 ms. (org.apache.kafka.storage.internals.log.ProducerStateManager)
[2023-12-27 16:59:24,842] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:27,204] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:27,750] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group my-loco-group in Empty state. Created a new member id loko-scheduler-7dda2658-3109-485a-a56c-dd6f80235e3d and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:27,580] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2023-12-27 16:59:28,190] INFO [GroupCoordinator 0]: Preparing to rebalance group my-loco-group in state PreparingRebalance with old generation 201 (__consumer_offsets-2) (reason: Adding new member loko-scheduler-7dda2658-3109-485a-a56c-dd6f80235e3d with group instance id None; client reason: not provided) (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:27,781] INFO Socket connection established, initiating session, client: /[0:0:0:0:0:0:0:1]:59759, server: localhost/[0:0:0:0:0:0:0:1]:2181 (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:28,959] INFO [GroupCoordinator 0]: Stabilized group my-loco-group generation 202 (__consumer_offsets-2) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:29,876] INFO Session establishment complete on server localhost/[0:0:0:0:0:0:0:1]:2181, session id = 0x10023a87fc80003, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2023-12-27 16:59:30,243] INFO [GroupCoordinator 0]: Assignment received from leader loko-scheduler-7dda2658-3109-485a-a56c-dd6f80235e3d for group my-loco-group for generation 202. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2023-12-27 16:59:31,794] INFO Stat of the created znode at /brokers/ids/0 is: 235,235,1703671170888,1703671170888,1,0,0,72096800643219459,214,0,235
 (kafka.zk.KafkaZkClient)
[2023-12-27 16:59:32,720] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://DESKTOP-E5VJCT2:9092, czxid (broker epoch): 235 (kafka.zk.KafkaZkClient)
[2023-12-27 16:59:31,827] INFO [MetadataCache brokerId=0] Updated cache from existing Some(Features(version=3.6-IV2, finalizedFeatures={}, finalizedFeaturesEpoch=0)) to latest Features(version=3.6-IV2, finalizedFeatures={}, finalizedFeaturesEpoch=0). (kafka.server.metadata.ZkMetadataCache)
[2023-12-27 16:59:35,854] WARN fsync-ing the write ahead log in SyncThread:0 took 1728ms which will adversely effect operation latency.File size is 67108880 bytes. See the ZooKeeper troubleshooting guide (org.apache.zookeeper.server.persistence.FileTxnLog)
[2023-12-27 16:59:50,521] WARN Failed atomic move of G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.cleaned to G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.swap retrying with a non-atomic move (org.apache.kafka.common.utils.Utils)
java.nio.file.FileSystemException: G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.cleaned -> G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.swap: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:978)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:227)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:495)
	at kafka.log.LocalLog$.$anonfun$replaceSegments$4(LocalLog.scala:861)
	at kafka.log.LocalLog$.$anonfun$replaceSegments$4$adapted(LocalLog.scala:861)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.replaceSegments(LocalLog.scala:861)
	at kafka.log.UnifiedLog.replaceSegments(UnifiedLog.scala:2071)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:703)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:623)
	at kafka.log.Cleaner.$anonfun$doClean$6$adapted(LogCleaner.scala:622)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:622)
	at kafka.log.Cleaner.clean(LogCleaner.scala:579)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:444)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:416)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:395)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:381)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
[2023-12-27 16:59:50,725] ERROR Failed to clean up log for __consumer_offsets-2 in dir G:\P79\GAP\tmp\kafka-logs due to IOException (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.nio.file.FileSystemException: G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.cleaned -> G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.swap: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:982)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:227)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:495)
	at kafka.log.LocalLog$.$anonfun$replaceSegments$4(LocalLog.scala:861)
	at kafka.log.LocalLog$.$anonfun$replaceSegments$4$adapted(LocalLog.scala:861)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.replaceSegments(LocalLog.scala:861)
	at kafka.log.UnifiedLog.replaceSegments(UnifiedLog.scala:2071)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:703)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:623)
	at kafka.log.Cleaner.$anonfun$doClean$6$adapted(LogCleaner.scala:622)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:622)
	at kafka.log.Cleaner.clean(LogCleaner.scala:579)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:444)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:416)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:395)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:381)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
	Suppressed: java.nio.file.FileSystemException: G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.cleaned -> G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.swap: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1432)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:978)
		... 20 more
[2023-12-27 16:59:50,922] WARN [ReplicaManager broker=0] Stopping serving replicas in dir G:\P79\GAP\tmp\kafka-logs (kafka.server.ReplicaManager)
[2023-12-27 16:59:51,118] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-37, __consumer_offsets-38, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, loko-data-0, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2023-12-27 16:59:51,459] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-37, __consumer_offsets-38, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, loko-data-0, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2023-12-27 16:59:51,859] ERROR Failed to clean up log for __consumer_offsets-2 in dir G:\P79\GAP\tmp\kafka-logs due to IOException (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.nio.file.FileSystemException: G:\P79\GAP\tmp\kafka-logs\__consumer_offsets-2\00000000000000000000.timeindex.cleaned: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at kafka.log.UnifiedLog$.deleteFileIfExists(UnifiedLog.scala:1966)
	at kafka.log.LogSegment$.deleteIfExists(LogSegment.scala:684)
	at kafka.log.LocalLog$.createNewCleanedSegment(LocalLog.scala:948)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:653)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:623)
	at kafka.log.Cleaner.$anonfun$doClean$6$adapted(LogCleaner.scala:622)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:622)
	at kafka.log.Cleaner.clean(LogCleaner.scala:579)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:444)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:416)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:395)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:381)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
[2023-12-27 16:59:51,940] WARN [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,__consumer_offsets-30,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-37,__consumer_offsets-38,__consumer_offsets-13,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,__consumer_offsets-46,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-15,__consumer_offsets-24,__consumer_offsets-17,__consumer_offsets-48,__consumer_offsets-19,__consumer_offsets-11,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,__consumer_offsets-14,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,__consumer_offsets-12,loko-data-0,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory G:\P79\GAP\tmp\kafka-logs. (kafka.server.ReplicaManager)
[2023-12-27 16:59:52,618] WARN Stopping serving logs in dir G:\P79\GAP\tmp\kafka-logs (kafka.log.LogManager)
[2023-12-27 16:59:53,164] ERROR Shutdown broker because all log dirs in G:\P79\GAP\tmp\kafka-logs have failed (kafka.log.LogManager)
[2023-12-27 16:59:55,305] WARN Close of session 0x10023a87fc80003 (org.apache.zookeeper.server.NIOServerCnxn)
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:331)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
